# Generated by Django 4.1.5 on 2023-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0003_collectiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondata',
            name='previousCollectionID',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
