# Generated by Django 4.1.5 on 2023-01-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0004_alter_collectiondata_previouscollectionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiondata',
            name='companyId',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='modeOfBusiness',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='phoneNumber',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='CollectionData',
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
        migrations.DeleteModel(
            name='ModeOfBusiness',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
