# Generated by Django 4.1.5 on 2023-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='companyName',
            field=models.CharField(max_length=200),
        ),
    ]
