# Generated by Django 4.1.5 on 2023-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0007_alter_companydetails_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='collectiondata',
            name='enquiry',
            field=models.ManyToManyField(blank=True, default='', to='TrackerApp.enquiry'),
        ),
    ]
