# Generated by Django 4.1.5 on 2023-01-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0010_userlocation_totaldistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyId', to='TrackerApp.companydetails'),
        ),
    ]
