# Generated by Django 4.1.5 on 2023-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0011_alter_phonenumber_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Active'), (1, 'Active'), (2, 'Hold')], default=3),
        ),
    ]
